name: add to sentry

on:
  push:
    branches-ignore:
      - 'gh-pages'
      - 'gh-pages-history'
    tags-ignore:
      - '*'

jobs:
  sentry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: install sentry cli
        run: curl -sL https://sentry.io/get-cli/ | bash

      - name: create sentry release
        env:
          SENTRY_AUTH_TOKEN: ${{secrets.SENTRY_TOKEN}}
          SENTRY_ORG: myetherwallet-inc
        run: |
          VERSION=$GITHUB_SHA
          sentry-cli releases new -p myetherwallet $VERSION
          sentry-cli releases set-commits $VERSION --auto
          sentry-cli releases finalize $VERSION
