name: add to sentry

on:
  push:
    branches-ignore:
      - 'gh-pages'
      - 'gh-pages-history'
    tags-ignore:
      - '*'

jobs:
  sentry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: install sentry cli
        run: curl -sL https://sentry.io/get-cli/ | bash

      - name: create sentry release
        env:
          SENTRY_AUTH_TOKEN: ${{secrets.SENTRY_TOKEN}}
          SENTRY_ORG: myetherwallet-inc
        run: |
          VERSION=$GITHUB_SHA
          START_SHA=`git rev-list -n 1 v5.6.0`
          END_SHA=`git rev-list -n 1 v5.6.1`
          sentry-cli releases new -p myetherwallet $VERSION
          sentry-cli releases set-commits --commit "MyEtherWallet/MyEtherWallet@$START_SHA..$END_SHA" $VERSION
          sentry-cli releases finalize $VERSION
