name: add to mewbuilds

on:
  push:
    branches-ignore:
      - 'master'
      - 'gh-pages'
      - 'gh-pages-history'
    tags-ignore:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          docker --version
          python --version
          pip --version
          docker build -t mew-build-container .
          docker run --rm -v `pwd`:/home:rw mew-build-container /bin/bash -c "npm install"
          docker run --rm -v `pwd`:/home:rw mew-build-container /bin/bash -c "npm run build:hash"
