name: add to mewbuilds

on:
  push:
    branches-ignore:
      - 'master'
      - 'gh-pages'
      - 'gh-pages-history'
    tags-ignore:
      - '*'

jobs:
  mewbuilds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup env
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X POST \
          -d "{\"body\": \"Copy of this build can be found at <br/>https://www.mewbuilds.com/build/${GITHUB_SHA}/index.html<br/> \
                            https://www.cloudflare-ipfs.com/ipfs/abc <br/> \
                            Virus Total analysis <br/> \
                            https://test.virustotal.link.notvalid\"}" \
                            "https://api.github.com/repos/${GITHUB_REPOSITORY}/commits/${GITHUB_SHA}/comments"
